disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - force_try
  - force_cast
  - type_body_length
  - function_body_length
  - shorthand_operator
  - file_length
  - cyclomatic_complexity
  - redundant_string_enum_value
  - nesting
  - redundant_optional_initialization
  - implicit_getter
  - large_tuple
  - todo
  - function_parameter_count
  - syntactic_sugar
  - weak_delegate
  - vertical_parameter_alignment
  - legacy_constructor
  - redundant_discardable_let
  - for_where
  - unused_optional_binding
  - notification_center_detachment

line_length:
  warning: 230
  error: 300

identifier_name:
  min_length: 2
  excluded:
    - a
    - b
    - c
    - d
    - i
    - j
    - u
    - v
    - x
    - y
    - r
    - g
    - Yi
    - Yim1
    - Xi
    - Xim1 
    - requiredField(String)

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - UXPandaV2Tests
  - UXPandaV2UITests_Snapshots
  - fastlane
